version: "3.8"

services:
  database:
    build:
      context: .
      dockerfile: Dockerfile.database
    ports:
     - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 20s
      retries: 10
    network_mode: bridge

  backend:
    depends_on:
      database:
        condition: service_healthy
    environment:
      - jasypt.encryptor.password=${JASYPT_PASSWORD}
    build:
      context: .
      dockerfile: Dockerfile.backend
      args:
        - JASYPT_PASSWORD=${JASYPT_PASSWORD}
    ports:
      - "8080:8080"
    links:
      - "database:localhost"
    network_mode: bridge

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    network_mode: bridge